version: "3.5"

services:
  sso:
    container_name: frontend
    # command: "yarn dev"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - " /app/node_modules"
    ports:
      - "3200:3200"
    environment:
      - NODE_ENV=production
